#### GLOBAL OPTIONS ####
# how many rows of feeds to create in the rendered HTML
rows: 3

# how many posts to display per feed in the rendered HTML
posts: 5

# tells the template whether to add a visual indicator for new post
new_post_age_threshold: 604800
#### GLOBAL OPTIONS ####


#### SITE OPTIONS ####
site:
  # the HTML and displayed title of the RSS landing page
  title: 'My RSS Feeds'
  # the HTML description used for metadata and SEO
  description: 'A nice RSS landing page for all my favorite feeds'
  # the HTML keyword metadata tag used for SEO
  keywords:
    - rss
    - landing
    - feeds
#### SITE OPTIONS ####


#### FEEDS LIST ####
# This is the main list of feeds that will be displayed in the renfered HTML.
# Each feed element under the feeds list should look like this:
#
# feeds:
#   - name: "my favorite RSS feed"
#     front_page: "https://my_fav_rss.com/frontpage"  # used for linking the feed title
#     rss_url: "https://my_fav_rss.com/rss.xml"  # the actual rss url from which posts are pulled
feeds:
  - name: "Stereophile"
    front_page: "https://www.stereophile.com/frontpage"
    rss_url: "https://www.stereophile.com/rss.xml"
  - name: "Absolute Sound"
    front_page: "https://www.theabsolutesound.com/"
    rss_url: "https://www.theabsolutesound.com/articles/feed"
  - name: "Enjoy The Music"
    front_page: "http://www.enjoythemusic.com/"
    rss_url: "http://www.enjoythemusic.com/enjoythemusic.xml"
  - name: "High Fidelity"
    front_page: "http://www.highfidelity.pl/"
    rss_url: "http://highfidelity.pl/rss2012.php"
  - name: "Positive Feedback"
    front_page: "https://positive-feedback.com/"
    rss_url: "https://positive-feedback.com/feed/atom/"
  - name: "Tone Audio"
    front_page: "https://www.tonepublications.com/"
    rss_url: "https://www.tonepublications.com/feed/"
#### FEEDS LIST ####

#### EXTRA_LINKS LIST ####
# This list is meant for presenting a number of sites that either may not have RSS, or for if you simply dont want to display posts. Each element of this list should look like this:
#
# extra_links:
#   - name: "A cool site"
#     link: "https://a_cool_site.com"
extra_links:
  - name: "6moons"
    link: "http://www.6moons.com"
  - name: "13th Note HiFi Reviews"
    link: "https://www.13thnote.net"
  - name: "Alpha Audio"
    link: "https://alpha-audio.net"
  - name: "Analog Dept"
    link: "http://theanalogdept.com/"
  - name: "Archimago’s Musings"
    link: "http://archimago.blogspot.com/"
  - name: "Audio Activity"
    link: "http://www.audio-activity.com/"
#### EXTRA_LINKS LIST ####
