#!/usr/bin/env python3

from datetime import timedelta

import json

from dateutil.parser import parse
from dateutil.tz import UTC
from dateutil.utils import today
from feedparser import parse as parse_feed
from jinja2 import Template


def get_feed(feed):
    for i in range(3):
        try:
            f = parse_feed(feed)
        except:
            continue
        if len(f.entries) > 0:
            return f
        else:
            if i == 2:
                return f


def main():
    with open("feeds.json", "r") as f:
        data = json.loads(f.read())

    for name, info in data["feeds"].items():
        info["posts"] = []
        feed_data = get_feed(info["feed"])
        for entry in feed_data.entries:
            if entry["title"] in [post["title"] for post in info["posts"]]:
                continue
            post_date = parse(entry["published"]).astimezone(UTC)
            info["posts"].append(
                {
                    "title": entry["title"],
                    "link": entry["link"],
                    "date": post_date,
                    "new": abs(today(UTC) - post_date) < timedelta(days=1),
                }
            )
            if len(info["posts"]) >= 5:
                info["posts"].sort(key=lambda x: x["date"], reverse=True)
                break
        print(f"posts captured for {name}")

    template = Template(open("template.html.j2").read())
    with open("rendered/index.html", "w") as f:
        f.write(template.render(data=data))
    print("template rendered")


if __name__ == "__main__":
    main()
